# Site settings
title: My Jekyll Test Site
email: remco@zuijlen.eu
description: "This is my Jekyll test setup."
baseurl: "/hello-world"
url: "http://www.zuijlen.eu/"

# Build settings
markdown: kramdown
permalink: pretty
