# Site settings
title: My Jekyll Site
email: github@zuijlen.eu
description: "This is my Jekyll setup."
baseurl: "/hello-world"
url: "http://www.zuijlen.eu"

github_user: "remcovz"
twitter_user: "remco72"

# Build settings
markdown: kramdown
permalink: pretty
